### ISSUE TITLE
Workflow for multiple runs?

### ISSUE THREAD

**Issue by justmytwospence** [Factual/drake#169]
I have a Drake workflow that works well for performing an analysis on one city, but I would like to run the analysis on other cities side by side in the same repo. `drake -v CITY=los_angeles` or drake -v CITY=san_francisco`. Is there a clean way to do this with Drake, or is it outside the intended use case?

**Comment by dirtyvagabond** [comment]
Without knowing more specifics about the behavioiur you're after, I'd suggest you read up on variables and branching:

* [variables](https://github.com/Factual/drake/wiki/Variables)
* [branching](https://docs.google.com/document/d/1bF-OKNLIG10v_lMes_m4yyaJtAaJKtdK0Jizvi_MNsg/edit#heading=h.3ygebqi)

If I'm understanding your question, you probably want to design your workflow so that the CITY variable is used to select the correct file (or more generally, the correct data input source). You can also make use of branching to keep your output conveniently organized.

Let us know whether this serves your purpose...

**Comment by justmytwospence** [comment]
Thanks, branching is the feature I was missing. It will still be a little tricky because some steps need their own branch, while other steps can be shared between branches, but hopefully I'll be able to figure something out.

**Comment by dirtyvagabond** [comment]
By rewriting the input/output files with an added branch tag, I think Drake mostly achieves what you're looking for. And you'll see that you can safely run different branches without worrying about them clobbering each other.

I'll close this for now, but please feel free to submit specific feature requests if you're branching experiments lead you to concrete ideas for how we could make this better.  8-]

**Comment by justmytwospence** [comment]
Cool thanks. Unfortunately I have zero working knowledge of clojure, but I really do think that the branching feature would be vastly improved by a way share dependencies between branches. There are a lot of analysis workflows that have a large overhead for a few setup steps, and then lighter analysis steps performed on top of that setup that should be branched.

**Comment by dirtyvagabond** [comment]
If I understand correctly, one thing you could do is build in the "large overhead" work as part of a script that gets called early in your workflow. That script need not be "thrown off" by the branching. That is, your script could certainly send output to a branch-specific destination while at the same time being aware of prebuilt dependencies.
