### ISSUE TITLE
stdout and stderr of task is being interleaved

### ISSUE THREAD

**Issue by pwaller** [Factual/drake#46]
This is what it should look like (when I run it standalone):

```
Hist('p0iso_tot') ph_analysis_isolation[0] / 1e3
Traceback (most recent call last):
  File "./histograms.py", line 69, in <module>
    main()
  File "./histograms.py", line 66, in main
    make_iso_plots(t, 0, sel)
  File "./histograms.py", line 35, in make_iso_plots
    print hist, "mgg", sel(*s)
NameError: global name 'hist' is not defined
```

This is what I get from drake (it's reproducible):

```
--- 0. Running (missing output): histograms.root <- data.root, histograms.py
T[r?a1c0e3b4ahcHki s(tm(o'spt0 irseoc_etnott ')c aplhl_ alnaasltys):i
s _ isFoillaet i"o.n/[h0i]s t/o g1rea3m
s.py", line 69, in <module>
    main()
  File "./histograms.py", line 66, in main
    make_iso_plots(t, 0, sel)
  File "./histograms.py", line 35, in make_iso_plots
    print hist, "mgg", sel(*s)
NameError: global name 'hist' is not defined
drake: shell command failed with exit code 1
```

Somehow the output is getting interleaved. I also see unprintable characters on the terminal.

**Comment by potash** [comment]
I can reliably reproduce this kind of garbling using psql. I tried to redirect stderr to stdout (2>&1) and vice versa (1>&2) but no luck. It makes it impossible to debug the errors in those scripts without running them outside of drake. Any ideas on how to fix this?

**Comment by potash** [comment]
Ah so the issue is actually solved with a redirect. In case you are interested in reproducing it here is an example Drakefile:

```
test <-
    ./test.sh 2>&1
```

and the script test.sh:
```
#!/bin/bash
echo 'before'
psql -c 'FAKE SQL'
echo 'after'
```

The redirect in the Drakefile fixes the problem. Note that without the echo statements there is no issue either.

One way to solve this for me is to simply "2>&1" every drake step. Since I always run drake interactively-- never to capture its output-- that poses no problems for my use case. Would you consider adding a command line flag that effectively does that? Would be much appreciated. Thanks!

**Comment by dirtyvagabond** [comment]
Hi @potash thanks for following up after all this time! I opened this per your request:
https://github.com/Factual/drake/issues/206
